# Generated by Django 4.1.7 on 2023-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_FullName', models.CharField(max_length=100)),
                ('sign_Username', models.CharField(max_length=100)),
                ('sign_Email', models.EmailField(max_length=100, unique=True)),
                ('sign_PhoneNumber', models.BigIntegerField(max_length=100)),
                ('sign_password', models.CharField(max_length=100)),
                ('sign_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
