# Generated by Django 4.1.7 on 2023-04-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signupdata',
            table='users_data',
        ),
    ]
