# Generated by Django 4.1.7 on 2023-05-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_packages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packages',
            table='packages_table',
        ),
    ]
