# Generated by Django 4.1.7 on 2023-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_packages_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Hotels', models.CharField(max_length=100)),
                ('UserRating', models.CharField(max_length=100)),
                ('PropertyType', models.CharField(max_length=100)),
                ('Chains', models.CharField(max_length=100)),
                ('Amenities', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'custom_table',
            },
        ),
    ]
