# Generated by Django 4.1.7 on 2023-05-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pid', models.IntegerField(max_length=10, unique=True)),
                ('price', models.IntegerField(max_length=100)),
                ('imgurl', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'destination_table',
            },
        ),
    ]
